ERROR:__main__:Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 42, in main
    args = parse_args()
NameError: name 'parse_args' is not defined
ERROR:__main__:Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 42, in main
    args = parse_args()
NameError: name 'parse_args' is not defined
2018-11-05 19:40:41,878 - Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 42, in main
    args = parse_args()
NameError: name 'parse_args' is not defined
2018-11-05 19:40:57,143 - CLI args: Namespace()
2018-11-05 19:40:57,152 - Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 49, in main
    start_flask_server()
  File ".\wittymail_web_gui.py", line 32, in start_flask_server
    import wittymail_server
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 4, in <module>
    sys.path.append(os.path.abspath(os.path.join(os.curdir, '..', '..')))
NameError: name 'sys' is not defined
2018-11-05 19:42:20,581 - CLI args: Namespace()
2018-11-05 19:42:20,591 - Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 49, in main
    start_flask_server()
  File ".\wittymail_web_gui.py", line 32, in start_flask_server
    import wittymail_server
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 5, in <module>
    sys.path.append(os.path.abspath(os.path.join(os.curdir, '..', '..')))
NameError: name 'os' is not defined
2018-11-05 19:42:34,772 - CLI args: Namespace()
2018-11-05 19:51:46,077 - CLI args: Namespace()
2018-11-05 19:51:46,336 - WittyMail REST API startup failed
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 29, in <module>
    CORS(app)
NameError: name 'app' is not defined
2018-11-05 19:52:16,927 - CLI args: Namespace()
2018-11-05 19:52:17,133 - WittyMail REST API startup failed
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 32, in <module>
    import default_routes
ModuleNotFoundError: No module named 'default_routes'
2018-11-05 19:52:44,362 - CLI args: Namespace()
2018-11-05 19:52:44,369 - Failed to start web server
Traceback (most recent call last):
  File ".\wittymail_web_gui.py", line 49, in main
    start_flask_server()
  File ".\wittymail_web_gui.py", line 32, in start_flask_server
    import wittymail_server
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 33
    import default_routes
         ^
SyntaxError: invalid syntax
2018-11-05 19:52:51,541 - CLI args: Namespace()
2018-11-05 19:52:51,746 - WittyMail REST API startup failed
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 33, in <module>
    import default_routes
ModuleNotFoundError: No module named 'default_routes'
2018-11-05 19:53:16,404 - CLI args: Namespace()
2018-11-05 19:53:16,601 - WittyMail REST API startup failed
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 32, in <module>
    import wittymail_server.default_routes
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\default_routes.py", line 4, in <module>
    sys.path.append(os.path.abspath(os.path.join(os.curdir, '..', '..')))
NameError: name 'sys' is not defined
2018-11-05 19:53:43,440 - CLI args: Namespace()
2018-11-05 19:53:43,638 - WittyMail REST API startup failed
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\__init__.py", line 32, in <module>
    import wittymail_server.default_routes
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\default_routes.py", line 14, in <module>
    @app.route("/")
NameError: name 'app' is not defined
2018-11-05 19:53:55,577 - CLI args: Namespace()
2018-11-05 19:53:55,984 -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-05 19:53:56,169 - Exception on / [GET]
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\default_routes.py", line 19, in index
    return send_file(os.path.join(base_path, "static" , "index.html"))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\personal\\git\\wittymail\\backend\\webserver\\..\\static\\index.html'
2018-11-05 19:53:56,180 - 127.0.0.1 - - [05/Nov/2018 19:53:56] "GET / HTTP/1.1" 500 -
2018-11-05 19:53:56,420 - 127.0.0.1 - - [05/Nov/2018 19:53:56] "GET /favicon.ico HTTP/1.1" 404 -
2018-11-05 19:53:56,815 - Exception on / [GET]
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\default_routes.py", line 19, in index
    return send_file(os.path.join(base_path, "static" , "index.html"))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\personal\\git\\wittymail\\backend\\webserver\\..\\static\\index.html'
2018-11-05 19:53:56,824 - 127.0.0.1 - - [05/Nov/2018 19:53:56] "GET / HTTP/1.1" 500 -
2018-11-05 19:56:29,381 - CLI args: Namespace(skip_opening_browser=True)
2018-11-05 19:56:29,731 -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-05 19:56:30,915 - Exception on / [GET]
Traceback (most recent call last):
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\personal\git\wittymail\backend\webserver\wittymail_server\default_routes.py", line 19, in index
    return send_file(os.path.join(base_path, "static" , "index.html"))
  File "D:\personal\git\wittymail\backend\ve\lib\site-packages\flask\helpers.py", line 588, in send_file
    file = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\personal\\git\\wittymail\\backend\\webserver\\..\\static\\index.html'
2018-11-05 19:56:30,928 - 127.0.0.1 - - [05/Nov/2018 19:56:30] "GET / HTTP/1.1" 500 -
2018-11-05 19:57:53,382 - CLI args: Namespace(skip_opening_browser=True)
2018-11-05 19:57:53,697 -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-05 19:59:06,844 - CLI args: Namespace(skip_opening_browser=True)
2018-11-05 19:59:07,161 -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-05 19:59:12,257 - 127.0.0.1 - - [05/Nov/2018 19:59:12] "GET /api.version HTTP/1.1" 404 -
2018-11-05 19:59:16,468 - 127.0.0.1 - - [05/Nov/2018 19:59:16] "GET /api/version HTTP/1.1" 200 -
2018-11-05 20:00:25,731 MainThread __main__     DEBUG    CLI args: Namespace(skip_opening_browser=True)
2018-11-05 20:00:26,065 MainThread werkzeug     INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-05 20:00:59,268 MainThread __main__     DEBUG    | CLI args: Namespace(skip_opening_browser=True)
2018-11-05 20:00:59,613 MainThread werkzeug     INFO     |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
